### ISSUE TITLE
SimpleModel Encoder 

### ISSUE THREAD

**Issue by skekre98** [skekre98/simple_learn#50]
**Description of feature/enhancement**
Implement encoder class for SimpleModels so they can be leveraged in methods such as` __str__` and `__repr__`.

**Description of implementation**
Don't have anything specific in mind at the moment, but we will need to handle cases such as type conversion.

**Why this is a good feature/enhancement**
This will allow us to encode general purpose SimpleModel information in a separate module.

**Additional context**
n/a

**Comment by skekre98** [comment]
@Turtle24 I have created this issue to keep track of encoder features

**Comment by Turtle24** [comment]
@skekre98 here's a bit more context. Hopefully this helps 😃

This is the import ```from  simple_learn.encoders import simple_model_encoder``` for further context.

So far the ```npEncoder``` is just sub class of the ```json.JSONEncoder``` class. When you ```def default``` it returns a serializable object for the int32 that's passed in. The if statement ```isinstance``` checks if the object is ```np.int32``` and then returns an ```int(object)``` as to convert it. Otherwise the normal object is returned. 

```python
import json
import numpy as np

class npEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.int32):
            return int(obj)
        return json.JSONEncoder.default(self, obj)
```
This is the current use case for the ```npEncoder```.  ```cls=simple_model_encoder.npEncoder``` uses the complex subclass that was created.

```python
def __repr__(self):
        
        attr = {
            "Type": self.name,
            "Training Duration": "{}s".format(self.train_duration),
            "GridSearch Duration": "{}s".format(self.gridsearch_duration),
            "Parameters": self.attributes,
            "Metrics": self.metrics,
        }
        
        repr_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
        return repr_out
```
